### ISSUE TITLE
Where do the updates go?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sphinx-theme#11]
I have a small tweak(for now) I want to make to the CSS of this theme but, I am unsure where these should go. Is it in:

https://github.com/mdn/sphinx-theme/blob/master/mdn_theme/mdn/static/mozilla.css_t

or in

https://github.com/mozilla/kuma/blob/master/kuma/static/styles/sphinx.scss

The update is:

```
.highlighttable {
    width: 100%;
}

.highlighttable pre {
	margin: 0;
}
```

**Comment by stephaniehobson** [comment]
I'm not really sure. I've never updated the theme and we're constantly talking about killing it :P 

mozilla.css_t looks like it came from somewhere else so I'd put my changes in sphinx.scss.

**Comment by jwhitlock** [comment]
This theme is generated from the Kuma styles, and the changes go in Kuma. I am planning to switch to the [default](http://kuma.readthedocs.io/en/default-1361729/) or [alabaster](http://kuma.readthedocs.io/en/alabaster-1361729/) theme when I have an hour.  I prefer the alabaster theme, but I think @stephaniehobson wanted to try a different body type face.

I don't plan on regenerating this theme for the new MDN style, and it will probably break after the AWS move.
